version: '3.8'

services:
  app:
    container_name: poke_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      DB_URL: jdbc:mysql://db:3308/POKE_DB
      DB_USERNAME: root
      DB_PASSWORD: toor
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: POKE_DB
      MYSQL_ROOT_PASSWORD: toor
